# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  workflow_dispatch:

jobs:
  build-n-publish:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: install dependencies
      run: |
       python -m pip install --upgrade pip
       pip install flake8 black build twine
       pip install .
       pip install -r requirements-dev.txt
    - name: runnig some pytest
      run: |
           coverage run -m pytest
           coverage report -m
           codecov 
           black .
    - name: Lint with flake8
      run: |
            # stop the build if there are Python syntax errors or undefined names
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            # exit-zero treats all errors as warnings.
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build binary wheel and a source tarball
      run: python setup.py sdist
    - name: build the documentation
      run: make -C docs html
    - name: deploy docs to github-page
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
          
    
       
 
  
    
    
